# 'bundle exec jekyll serve'

title: most weekdays.
email: dieter@waypastokay.com
author: dc randolph
license: licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>.
description: >-
  what I am thinking about and working on, typically updated mondays - fridays.
notice: >-
  all contents were created by humans. no AI was involved.
baseurl: ""
url: "https://waypastokay.com"
permalink: /posts/:title/
instagram_username: waypastokay
youtube_username: waypastokay
threads_username: waypastokay
pinterest_username: waypastokay
bluesky_username: waypastokay.bsky.social
buymeacoffee_username: waypastokay

header_pages:
  - index.md
  - about.md
  - tags.md

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
